url: http://tom.lezotte.net
baseurl: /

# Site settings
title: Tom LeZotte
email: tom@lezotte.net
description: ""

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/tomlezotte/
  - title: stack-overflow
    url: https://stackoverflow.com/users/290908/tom
  - title: github
    url: https://github.com/tlezotte
  - title: envelope
    url: mailto:tom@lezotte.net


# Build settings
markdown: kramdown
permalink: pretty